version: '2'
services:
    nginx:
        build: ./nginx
        links:
            - django
        volumes:
            - ./app/static:/mnt
        ports:
            - 80:80

    django:
        build: ./app
        links:
            - db
        volumes:
            - ./app/:/mnt
        env_file: ./db/.env
        working_dir: /mnt
        tty: true

    db:
        build: ./db
        env_file: ./db/.env
