# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tirac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='tirac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac'),
        ),
    ]
