# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('audio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Iine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tirac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('md', models.CharField(max_length=1000)),
                ('header_img', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='settag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tags'),
        ),
        migrations.AddField(
            model_name='settag',
            name='tirac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac'),
        ),
        migrations.AddField(
            model_name='score',
            name='tirac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac'),
        ),
        migrations.AddField(
            model_name='iine',
            name='tirac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac'),
        ),
        migrations.AddField(
            model_name='iine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='tirac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
