# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('tirac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac')),
            ],
        ),
    ]
