# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_iine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='settag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tags'),
        ),
        migrations.AddField(
            model_name='settag',
            name='tirac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tirac'),
        ),
    ]
