# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170316_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
