# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170316_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='tagname',
        ),
    ]
